# app/controller/contracts.py
from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Protocol, TypeAlias, runtime_checkable

from app.model.domain.entities import SettingsSnapshot, TranscriptionSessionRequest
from app.model.domain.results import SourceExpansionResult

ErrorParams: TypeAlias = dict[str, Any]
ProbeRow: TypeAlias = dict[str, Any]
ProbeBatch: TypeAlias = list[ProbeRow]
SourcePayload: TypeAlias = dict[str, Any]
SourceEntry: TypeAlias = str | SourcePayload
ProbeMeta: TypeAlias = dict[str, Any]
SettingsPayload: TypeAlias = dict[str, Any]
WorkerRef: TypeAlias = Any
SpectrumValues: TypeAlias = Sequence[float]


@runtime_checkable
class FilesCoordinatorProtocol(Protocol):
    def is_probe_running(self) -> bool: ...
    def is_transcribing(self) -> bool: ...
    def is_expanding(self) -> bool: ...
    def start_probe(self, entries: list[SourcePayload]) -> WorkerRef | None: ...
    def cancel_probe(self) -> None: ...
    def start_transcription(
        self,
        *,
        entries: list[SourceEntry],
        session_request: TranscriptionSessionRequest,
    ) -> WorkerRef | None: ...
    def cancel_transcription(self) -> None: ...
    def resolve_conflict(self, action: str, new_stem: str = "") -> None: ...
    def save_quick_options(self, payload: SettingsPayload) -> WorkerRef | None: ...
    def expand_manual_input(self, raw: str) -> WorkerRef | None: ...
    def expand_local_paths(self, paths: list[str], origin_kind: str) -> WorkerRef | None: ...
    def cancel_expansion(self) -> None: ...


class FilesPanelViewProtocol(Protocol):
    def bind_coordinator(self, coordinator: FilesCoordinatorProtocol) -> None: ...
    def on_runtime_state_changed(
        self,
        *,
        transcription_ready: bool,
        transcription_error_key: str | None,
        transcription_error_params: ErrorParams,
        translation_ready: bool,
        translation_error_key: str | None,
        translation_error_params: ErrorParams,
    ) -> None: ...
    def on_meta_rows_ready(self, batch: ProbeBatch) -> None: ...
    def on_meta_item_error(self, key: str, err_key: str, params: ErrorParams) -> None: ...
    def on_meta_finished(self) -> None: ...
    def on_global_progress(self, value: int) -> None: ...
    def on_item_status(self, key: str, status: str) -> None: ...
    def on_item_progress(self, key: str, pct: int) -> None: ...
    def on_item_path_update(self, old_key: str, new_key: str) -> None: ...
    def on_transcript_ready(self, key: str, transcript_path: str) -> None: ...
    def on_item_error(self, key: str, err_key: str, params: ErrorParams) -> None: ...
    def on_item_output_dir(self, key: str, out_dir: str) -> None: ...
    def on_conflict_check(self, stem: str, existing_dir: str) -> None: ...
    def on_session_done(
        self,
        session_dir: str,
        processed_any: bool,
        had_errors: bool,
        was_cancelled: bool,
    ) -> None: ...
    def on_transcribe_finished(self) -> None: ...
    def refresh_defaults_from_settings(self) -> None: ...
    def on_quick_options_save_error(self, key: str, params: ErrorParams) -> None: ...
    def on_expansion_busy_changed(self, busy: bool) -> None: ...
    def on_expansion_status_changed(self, key: str, params: ErrorParams) -> None: ...
    def on_expansion_ready(self, result: SourceExpansionResult) -> None: ...
    def on_expansion_error(self, key: str, params: ErrorParams) -> None: ...


@runtime_checkable
class LiveCoordinatorProtocol(Protocol):
    def is_running(self) -> bool: ...
    def start_session(
        self,
        *,
        device_name: str = "",
        source_language: str = "",
        target_language: str = "",
        translate_enabled: bool = False,
        preset_id: str = "default",
        output_mode: str = "cumulative",
    ) -> WorkerRef | None: ...
    def cancel(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def list_input_devices(self) -> list[str]: ...
    def save_quick_options(self, payload: SettingsPayload) -> WorkerRef | None: ...


class LivePanelViewProtocol(Protocol):
    def bind_coordinator(self, coordinator: LiveCoordinatorProtocol) -> None: ...
    def refresh_defaults_from_settings(self) -> None: ...
    def on_runtime_state_changed(
        self,
        *,
        transcription_ready: bool,
        transcription_error_key: str | None,
        transcription_error_params: ErrorParams,
        translation_ready: bool,
        translation_error_key: str | None,
        translation_error_params: ErrorParams,
    ) -> None: ...
    def on_worker_failed(self, key: str, params: ErrorParams) -> None: ...
    def on_status(self, msg: str) -> None: ...
    def on_detected_language(self, lang: str) -> None: ...
    def on_source_text(self, text: str) -> None: ...
    def on_target_text(self, text: str) -> None: ...
    def on_archive_source_text(self, text: str) -> None: ...
    def on_archive_target_text(self, text: str) -> None: ...
    def on_spectrum(self, values: SpectrumValues) -> None: ...
    def on_live_finished(self) -> None: ...
    def on_quick_options_save_error(self, key: str, params: ErrorParams) -> None: ...


@runtime_checkable
class DownloaderCoordinatorProtocol(Protocol):
    def is_downloading(self) -> bool: ...
    def is_probe_running(self, job_key: str | None = None) -> bool: ...
    def is_expanding(self) -> bool: ...
    def start_probe(self, *, job_key: str, url: str) -> WorkerRef | None: ...
    def cancel_probe(self, job_key: str) -> None: ...
    def cancel_all_probes(self) -> None: ...
    def expand_manual_input(self, raw: str) -> WorkerRef | None: ...
    def cancel_expansion(self) -> None: ...
    def start_download(
        self,
        *,
        url: str,
        kind: str,
        quality: str,
        ext: str,
        audio_lang: str | None = None,
    ) -> WorkerRef | None: ...
    def cancel_download(self) -> None: ...
    def resolve_duplicate(self, action: str, new_name: str = "") -> None: ...


class DownloaderPanelViewProtocol(Protocol):
    def bind_coordinator(self, coordinator: DownloaderCoordinatorProtocol) -> None: ...
    def on_probe_ready(self, job_key: str, meta: ProbeMeta) -> None: ...
    def on_expansion_busy_changed(self, busy: bool) -> None: ...
    def on_expansion_status_changed(self, key: str, params: ErrorParams) -> None: ...
    def on_expansion_ready(self, result: SourceExpansionResult) -> None: ...
    def on_expansion_error(self, key: str, params: ErrorParams) -> None: ...
    def on_probe_error(self, job_key: str, err_key: str, params: ErrorParams) -> None: ...
    def on_progress_pct(self, pct: int) -> None: ...
    def on_stage_changed(self, stage: str) -> None: ...
    def on_duplicate_check(self, title: str, expected: str) -> None: ...
    def on_download_finished(self, path: object) -> None: ...
    def on_download_error(self, err_key: str, params: ErrorParams) -> None: ...
    def on_download_cancelled(self) -> None: ...
    def on_download_cycle_finished(self) -> None: ...


class SettingsCoordinatorProtocol(Protocol):
    def is_busy(self) -> bool: ...
    def load(self) -> WorkerRef | None: ...
    def save(self, payload: SettingsPayload | None = None) -> WorkerRef | None: ...
    def save_ui_state(self, payload: SettingsPayload | None = None) -> WorkerRef | None: ...
    def restore_defaults(self) -> WorkerRef | None: ...
    def cancel(self) -> None: ...


class SettingsPanelViewProtocol(Protocol):
    def bind_coordinator(self, coordinator: SettingsCoordinatorProtocol) -> None: ...
    def on_settings_loaded(self, snap: SettingsSnapshot) -> None: ...
    def on_saved(self, action: str, snap: SettingsSnapshot) -> None: ...
    def on_error(self, key: str, params: ErrorParams) -> None: ...


class MainWindowPanelsHostProtocol(Protocol):
    files_panel: FilesPanelViewProtocol | None
    live_panel: LivePanelViewProtocol | None
    downloader_panel: DownloaderPanelViewProtocol | None
    settings_panel: SettingsPanelViewProtocol | None
